name: CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  job1:
    name: Job copy project on server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

        



      - name: Deploying to "_nubezar.tech/". (/domains/nubezar.tech/public_html/_nubezartech/)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          source: "!src/vendor,!src/vendor/*,src/*"
          target: "public_html/sau_api/"
          strip_components: 1

